### ISSUE TITLE
Latest release on the main page not actually showing the latest

### ISSUE THREAD

**Issue by MastaCoder** [getreflect/get-reflect#28]
The latest release on the homepage doesn't seem to show the correct latest release. On latest.html, the latest release is marked as 1.2.0 compared to the one shown on the homepage (below) of 1.1.0.

![image](https://user-images.githubusercontent.com/9423347/86522642-1f887b80-be2f-11ea-9c0e-a00300ad5934.png)

**Comment by jackyzha0** [comment]
thanks for letting us know, @MastaCoder!
